CREATE TABLE solicitacao (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL,
    email VARCHAR(155) NOT NULL,
    cargo_desejado VARCHAR(100),
    status ENUM('PENDENTE','APROVADO','RECUSADO') DEFAULT 'PENDENTE',
    dt_ult_alt DATETIME DEFAULT CURRENT_TIMESTAMP
);
