CREATE TABLE usuario (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL,
    email VARCHAR(155) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    first_login BOOLEAN DEFAULT TRUE,
    role_id INT NOT NULL,
    dt_ult_alt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_role FOREIGN KEY (role_id) REFERENCES role(id)
);