INSERT IGNORE INTO etapa (tipo, nome) VALUES
('PEDIDO', 'PENDENTE'),
('PEDIDO', 'AGUARDANDO ORÇAMENTO'),
('PEDIDO', 'ANÁLISE DO ORÇAMENTO'),
('PEDIDO', 'ORÇAMENTO APROVADO'),
('PEDIDO', 'SERVIÇO AGENDADO'),
('PEDIDO', 'SERVIÇO EM EXECUÇÃO'),
('PEDIDO', 'CONCLUÍDO');

INSERT IGNORE INTO status (tipo, nome) VALUES
('PEDIDO', 'ATIVO'),
('PEDIDO', 'EM ANDAMENTO'),
('PEDIDO', 'FINALIZADO'),
('PEDIDO', 'PENDENTE'),
('PEDIDO', 'CANCELADO');
