name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validar se a tag aponta para commit da main
        run: |
          git fetch origin main
          if ! git branch -r --contains "$GITHUB_SHA" | grep -q "origin/main"; then
            echo "Tag fora da main. Build interrompido para evitar deploy conflitante."
            exit 1
          fi

      - name: Build JAR
        run: mvn clean package -DskipTests
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/meu-app:latest .
      
      - name: Adicionar Tag para a imagem
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/meu-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/meu-app:${{ github.sha }}
      
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/meu-app:latest 